In [1]:
import pandas as pd
import numpy as np
import os
from pathlib import Path
os.chdir(Path().resolve().parent)
from src.io_file import load_dataset
from src.utils.smart_format import smart_format
from src.features import extend_eurostat_dataset

### Waste generation by country, Nace rev2 activity and waste type (EWC-Stat 4 codes)

In [9]:
wasgen = extend_eurostat_dataset(load_dataset("env_wasgen"),['nace_r2','waste','geo'])
wasgen.head()

,freq,unit,hazard,nace_r2,nace_r2_description,waste,waste_description,geo,geo_description,2004,2006,2008,2010,2012,2014,2016,2018,2020,2022
0,A,KG_HAB,HAZ,A,"Agriculture, forestry and fishing",PRIM,Primary waste (TOTAL minus SEC),AL,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,A,KG_HAB,HAZ,A,"Agriculture, forestry and fishing",PRIM,Primary waste (TOTAL minus SEC),AT,Austria,NaN,NaN,NaN,9.0,1.0,1.0,NaN,1.0,1.0,1.0
2,A,KG_HAB,HAZ,A,"Agriculture, forestry and fishing",PRIM,Primary waste (TOTAL minus SEC),BA,Bosnia and Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3,A,KG_HAB,HAZ,A,"Agriculture, forestry and fishing",PRIM,Primary waste (TOTAL minus SEC),BE,Belgium,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0
4,A,KG_HAB,HAZ,A,"Agriculture, forestry and fishing",PRIM,Primary waste (TOTAL minus SEC),BG,Bulgaria,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [15]:
wasgen['waste_description'].unique()

array(['Primary waste (TOTAL minus SEC)',
       'Secondary waste (W033+W103+W128_13)', 'Total waste',
       'Waste excluding major mineral wastes',
       'Chemical and medical wastes (subtotal)', 'Spent solvents',
       'Acid, alkaline or saline wastes', 'Used oils', 'Chemical wastes',
       'Industrial effluent sludges',
       'Sludges and liquid wastes from waste treatment',
       'Health care and biological wastes',
       'Metallic wastes (W061+W062+W063)', 'Metal wastes, ferrous',
       'Metal wastes, non-ferrous',
       'Metal wastes, mixed ferrous and non-ferrous',
       'Recyclable wastes (subtotal, W06+W07 except W077)',
       'Glass wastes', 'Paper and cardboard wastes', 'Rubber wastes',
       'Plastic wastes', 'Wood wastes', 'Textile wastes',
       'Waste containing PCB',
       'Equipment (subtotal, W077+W08A+W081+W0841)', 'Discarded vehicles',
       'Batteries and accumulators wastes',
       'Discarded equipment (except discarded vehicles and batteries and accumulators waste) (W08 except W081, W0841)',
       'Animal and mixed food waste', 'Vegetal wastes',
       'Animal faeces, urine and manure',
       'Mixed ordinary wastes (subtotal, W101+W102+W103)',
       'Household and similar wastes',
       'Mixed and undifferentiated materials', 'Sorting residues',
       'Common sludges', 'Mineral and solidified wastes (subtotal)',
       'Mineral waste from construction and demolition',
       'Combustion wastes', 'Soils',
       'Soils and dredging spoils (W126+W127, valid up to 2008)',
       'Dredging spoils',
       'Mineral wastes from waste treatment and stabilised wastes',
       'Mineral wastes (except combustion wastes, contaminated soils and polluted dredging spoils) (W121+122+W123+W125+W126, valid up to 2008)',
       'Other mineral wastes (W122+W123+W125)',
       'Mineral waste (except non-hazardous dredging spoils, valid up to 2008)',
       'Solidified, stabilised or vitrified wastes (valid up to 2008)',
       'Animal and vegetal wastes (subtotal, W091+W092+W093)',
       'Animal and mixed food waste; vegetal wastes (W091+W092)'],
      dtype=object)

### Waste treatment by country, operations and waste type (EWC Stat 4 codes)

In [8]:
wastrt = extend_eurostat_dataset(load_dataset("env_wastrt"),['wst_oper','waste','geo'])
wastrt.head()

,freq,unit,hazard,wst_oper,wst_oper_description,waste,waste_description,geo,geo_description,2004,2006,2008,2010,2012,2014,2016,2018,2020,2022
0,A,KG_HAB,HAZ,DSP_I,Disposal - incineration (D10),DSP_OTH,Other disposed wastes (valid up to 2008),IS,Iceland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A,KG_HAB,HAZ,DSP_I,Disposal - incineration (D10),INC_OTH,Other incinerated wastes (valid up to 2008),AT,Austria,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A,KG_HAB,HAZ,DSP_I,Disposal - incineration (D10),INC_OTH,Other incinerated wastes (valid up to 2008),BE,Belgium,NaN,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A,KG_HAB,HAZ,DSP_I,Disposal - incineration (D10),INC_OTH,Other incinerated wastes (valid up to 2008),BG,Bulgaria,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A,KG_HAB,HAZ,DSP_I,Disposal - incineration (D10),INC_OTH,Other incinerated wastes (valid up to 2008),CY,Cyprus,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
wastrt['wst_oper_description'].unique()

array(['Disposal - incineration (D10)',
       'Disposal - landfill (D1, D5, D12)',
       'Disposal - landfill and other (D1-D7, D12)',
       'Disposal - other (D2-D4, D6-D7)', 'Recovery - backfilling',
       'Recovery - energy recovery (R1)', 'Recovery - recycling',
       'Recovery - recycling and backfilling (R2-R11)', 'Waste treatment'],
      dtype=object)

### Waste facilities per NUTS2 region

In [10]:
wasfac = extend_eurostat_dataset(load_dataset("env_wasfac"),['indic_env','wst_oper','geo'])
wasfac.head()

,freq,indic_env,indic_env_description,wst_oper,wst_oper_description,geo,geo_description,2004,2006,2008,2010,2012,2014,2016,2018,2020,2022
0,A,CAP,Capacity - tonnes per year,DSP_I,Disposal - incineration (D10),AT,Austria,2509116.0,1666130.0,1551000.0,1872000.0,100000.0,100000.0,100000.0,100000.0,NaN,NaN
1,A,CAP,Capacity - tonnes per year,DSP_I,Disposal - incineration (D10),AT1,Ostösterreich,1196600.0,880000.0,1150000.0,1476000.0,100000.0,100000.0,100000.0,100000.0,NaN,NaN
2,A,CAP,Capacity - tonnes per year,DSP_I,Disposal - incineration (D10),AT11,Burgenland,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,A,CAP,Capacity - tonnes per year,DSP_I,Disposal - incineration (D10),AT12,Niederösterreich,NaN,300000.0,430000.0,680000.0,0.0,0.0,0.0,0.0,0.0,0.0
4,A,CAP,Capacity - tonnes per year,DSP_I,Disposal - incineration (D10),AT13,Wien,836500.0,580000.0,720000.0,796000.0,100000.0,100000.0,100000.0,100000.0,NaN,NaN

In [12]:
wasfac['wst_oper_description'].unique()

array(['Disposal - incineration (D10)',
       'Disposal - landfill (D1, D5, D12)',
       'Disposal - landfill for inert waste',
       'Disposal - landfill for non-hazardous waste',
       'Disposal - landfill and other (D1-D7, D12)',
       'Disposal - other (D2-D4, D6-D7)', 'Recovery - backfilling',
       'Recovery - energy recovery (R1)', 'Recovery - recycling',
       'Recovery - recycling and backfilling (R2-R11)',
       'Disposal - landfill for hazardous waste'], dtype=object)

Also available datasets:

- Structered business statistics (SBS) per Nace 2 activity and NUTS2 region, -> allows for economic allocation of generated waste
- Material import dependency per country and material groups -> shows which countries are dependent on importing raw materials.

...and more